# Generated by Django 5.2.7 on 2025-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
